#ifndef PROJECTBOOM_CONFIGURATION_H
#define PROJECTBOOM_CONFIGURATION_H
// server configuration
#define SERVER_PORT 1234
// game configuration
#define MAP_SIZE 15
#define MAP_FIELD_SIZE 80
#define PLAYERS_QUANTITY 2      //max 4
#define PLAYERS_START_LIFES_QUANTITY 3
#define PLAYERS_START_BOMBS_QUANTITY 3
#define PLAYERS_START_BOMB_POWER 2
#define PROTECTION_DURATION 2000

#endif //PROJECTBOOM_CONFIGURATION_H
