#ifndef PROJECTBOOM_CONFIGURATION_H
#define PROJECTBOOM_CONFIGURATION_H
// server configuration
#define SERVER_PORT 1234
// game configuration
#define MAP_SIZE 10
#define MAP_FIELD_SIZE 30
#define PLAYERS_QUANTITY 3      //max 4
#define PLAYERS_START_LIFES_QUANTITY 3
#define PLAYERS_START_BOMBS_QUANTITY 3

#endif //PROJECTBOOM_CONFIGURATION_H
